### ISSUE TITLE
IPv4 not Supported on your current connection

### ISSUE THREAD

**Issue by Beaststriker** [DjNemas/NetCupDynDNS#1]
I dont know what i am doing wrong. I get the error in the headline. Here Also a picture of the command line:
![image](https://github.com/DjNemas/NetCupDynDNS/assets/42116283/e7a4dd4a-a41c-4646-8c92-dda0ef6566d8)

Are there any other settings to do? I start the application on my Windows Server 2016

Regard,
Stefan

**Comment by Beaststriker** [comment]
Here are more information from debugging site:
![image](https://github.com/DjNemas/NetCupDynDNS/assets/42116283/b4506d55-1c7c-4ea5-a402-df26af7a3415)

Regards

**Comment by DjNemas** [comment]
Hey thx for the Issue Report!
It seems there is trouble with the my-ip.io domain. I request this page to get a IPv4 or 6 response.
The Error Code of the Domain response says that you requested this side/domain to often.
How often did you start my DNS Tool?

**Comment by Beaststriker** [comment]
I have tried it 3 or 4 times. I found a solution. I tried an other provider and it works... i hope it helps.
![image](https://github.com/DjNemas/NetCupDynDNS/assets/42116283/79aedbf4-1a11-4b90-bcb6-625d046c51e4)

Regards Stefan

**Comment by DjNemas** [comment]
Perfekt!
Yes i need to rewrite this function and change this procedure. 
Or i may will implement an endpoint on my server with much lesser strict request limits.

I'll Close this Issue now. :)
